print("Hello world !")
print("chanz")
print("xyzzcc")
print("chandhinishri")

print("this is second day of git")
print("making changes in UI in main branch")
print("adding shri in shri branch")
print("adding new line")
print("checking revert 1 ")
